# Generated by Django 4.0.4 on 2022-04-25 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('surname', models.CharField(blank=True, max_length=40)),
                ('city', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('password1', models.CharField(max_length=40)),
                ('password2', models.CharField(max_length=40)),
                ('super_user', models.BooleanField()),
                ('user_auth', models.BooleanField()),
            ],
        ),
    ]
