# Generated by Django 4.0.4 on 2022-04-25 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodels',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='usermodels',
            name='super_user',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='usermodels',
            name='user_auth',
            field=models.BooleanField(blank=True),
        ),
    ]
