# Generated by Django 4.0.4 on 2022-04-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train_app', '0002_alter_usermodels_email_alter_usermodels_super_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodels',
            name='super_user',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usermodels',
            name='user_auth',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
