# Generated by Django 4.0.4 on 2022-05-04 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train_app', '0003_alter_usermodels_super_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_path', models.TextField()),
            ],
        ),
    ]
