# Generated by Django 4.0.4 on 2022-05-04 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train_app', '0004_trainpath'),
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_train', models.CharField(max_length=10)),
                ('name_train', models.CharField(blank=True, max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=40)),
                ('from_city_time', models.CharField(max_length=10)),
                ('to_city_time', models.CharField(max_length=10)),
                ('number_train', models.ManyToManyField(to='train_app.train')),
                ('train_path_id', models.ManyToManyField(to='train_app.trainpath')),
            ],
        ),
    ]
