# Generated by Django 4.0.4 on 2022-05-06 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('train_app', '0005_train_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='number_train',
        ),
        migrations.AddField(
            model_name='city',
            name='number_train',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='train_app.train'),
        ),
        migrations.RemoveField(
            model_name='city',
            name='train_path_id',
        ),
        migrations.AddField(
            model_name='city',
            name='train_path_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='train_app.trainpath'),
        ),
        migrations.AlterField(
            model_name='train',
            name='name_train',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
    ]
