# Generated by Django 4.0.4 on 2022-05-06 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train_app', '0006_remove_city_number_train_city_number_train_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainpath',
            old_name='train_path',
            new_name='long_train_path',
        ),
        migrations.AddField(
            model_name='trainpath',
            name='short_train_path',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
