# Generated by Django 4.0.4 on 2022-05-07 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train_app', '0007_rename_train_path_trainpath_long_train_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='to_city_time',
        ),
    ]
