# Generated by Django 4.0.4 on 2022-05-07 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train_app', '0008_remove_city_to_city_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='number_train',
            new_name='number_trains',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='train_path_id',
            new_name='train_paths',
        ),
    ]
