# Generated by Django 4.0.4 on 2022-05-07 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train_app', '0009_rename_number_train_city_number_trains_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='to_sity_time',
            field=models.IntegerField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='from_city_time',
            field=models.IntegerField(max_length=10),
        ),
    ]
