# Generated by Django 4.0.4 on 2022-05-07 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train_app', '0010_city_to_sity_time_alter_city_from_city_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='from_city_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='city',
            name='to_sity_time',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
