# Generated by Django 4.0.4 on 2022-05-07 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train_app', '0012_rename_to_sity_time_city_to_city_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TrainPath',
            new_name='TrainPaths',
        ),
        migrations.DeleteModel(
            name='UserModels',
        ),
    ]
