# Generated by Django 4.0.4 on 2022-05-07 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('train_app', '0013_rename_trainpath_trainpaths_delete_usermodels'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_train_car', models.CharField(max_length=100)),
                ('train_car_composition', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TypeTrainCars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_train_car', models.CharField(max_length=100)),
                ('number_of_seats', models.IntegerField()),
                ('number_of_rows', models.IntegerField()),
                ('place_size', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='train',
            name='train_composition',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='train_app.traincomposition'),
        ),
    ]
