# Generated by Django 4.0.4 on 2022-05-17 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('train_app', '0015_traincomposition_list_types_train_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='typetraincars',
            name='all_number_seats',
            field=models.IntegerField(default='0'),
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=100)),
                ('train', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='train_app.train')),
            ],
        ),
    ]
