# Generated by Django 4.0.4 on 2022-05-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train_app', '0016_typetraincars_all_number_seats_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='traincomposition',
            name='train_car_composition_json',
            field=models.JSONField(default=0),
        ),
    ]
