# Generated by Django 4.0.4 on 2022-05-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train_app', '0017_traincomposition_train_car_composition_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typetraincars',
            name='all_number_seats',
            field=models.IntegerField(default=dict),
        ),
    ]
