# Generated by Django 4.0.4 on 2022-05-31 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train_app', '0018_alter_typetraincars_all_number_seats'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tickets',
        ),
    ]
