# Generated by Django 4.0.4 on 2022-05-31 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train_app', '0019_delete_tickets'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_passenger', models.CharField(max_length=40)),
                ('surname_passenger', models.CharField(max_length=100)),
                ('number_train', models.CharField(max_length=10)),
                ('number_train_car', models.IntegerField()),
                ('number_seats', models.IntegerField()),
            ],
        ),
    ]
