# Generated by Django 4.0.4 on 2022-06-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train_app', '0020_tickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='from_city_time',
            field=models.CharField(default=None, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='to_city_time',
            field=models.CharField(default=None, max_length=40, null=True),
        ),
    ]
