# Generated by Django 4.0.4 on 2022-06-09 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train_app', '0021_alter_city_from_city_time_alter_city_to_city_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='arrival_city_time',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='tickets',
            name='from_city_time',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='tickets',
            name='leaves_city_time',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='tickets',
            name='train_path',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tickets',
            name='type_train_car',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
